[package]
name = "surveytrend_token"
version = "0.1.0"
edition = "2021"

[dependencies]
anchor-lang = "0.30.1"
anchor-spl = "0.30.1"
solana-program = "1.18.26"
serde = { version = "1.0", features = ["derive"] }
